# Import required Libraries


In [ ]:
import numpy as np
import pandas as pd
from numpy import random

In [ ]:
# WE import the files using pandas libraries and we visualize the dataframes
xls = pd.ExcelFile('ProjectData.xlsx')
df1 = pd.read_excel(xls, 'Project Data')
df2 = pd.read_excel(xls, 'Maintenance Type A Cost')

In [ ]:
df1

Origin City  Destination City  ...  Days of Week  Day of Week
0              3                 5  ...           NaN            0
1              3                13  ...           NaN            0
2             10                 6  ...           NaN            0
3             11                15  ...           NaN            0
4             15                 9  ...           NaN            0
..           ...               ...  ...           ...          ...
170            1                 7  ...           NaN            6
171            1                 9  ...           NaN            6
172            3                 4  ...           NaN            6
173           13                 1  ...           NaN            6
174           12                12  ...           NaN            6

[175 rows x 6 columns]

In [ ]:
df2

Aircraft  City 1  City 2  City 3  ...  City 12  City 13  City 14  City 15
0          1       6       1       1  ...       14        8       15       10
1          2      15      10       2  ...        5        5       14        6
2          3       5       4       1  ...        9        3        5        8
3          4      13       9      11  ...        6        7        9        7
4          5       6       1      14  ...       15        2        6       10
5          6       8       6       2  ...        7       14        1       10
6          7      14      11       6  ...        7       15        5        4
7          8      15       5       6  ...       10        4       13        9
8          9       6       1       1  ...       10        4        6        1
9         10       6       2      10  ...        9        7        8        6
10        11       6       1      14  ...        6        2       14       11
11        12      14      12       5  ...        5        1        2        1
12        13      14      11       6  ...        5        9        6       15
13        14       8       4       1  ...        8        7       10       10
14        15      14      11       6  ...        7       15        4        4
15        16      15       5      13  ...       14        8       14       11
16        17      10       4       9  ...       11        4       11        5
17        18       2       1      11  ...        6        1        6        4
18        19      10      14       1  ...       14       14       16        6
19        20       2      14       8  ...        7       14        7        1
20        21       4       6      15  ...        9        6        9       14
21        22      13       4      10  ...        7        6        3       10
22        23      13       4       4  ...       15        4       11        5
23        24       4       6      15  ...        9        6        9       14
24        25      13       4      10  ...        7        6        3       15

[25 rows x 16 columns]

# Demonstration of the Data Structures

In [ ]:
#We can create a NumPy ndarray object by using the array() function.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [ ]:
import pandas as pd
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [ ]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


# Main Algorithm 

In [ ]:
# 'i' is the index for planes (1 to n_p)
# 'j','k' is the index for cities (1 to n_c)
# 'd' is the index for days (1 to n_d), here (0 to 6)


# 'j(d)' is the node for city j on day d
# 'j(d-1)k(d)r' is the edge connecting city j on day d-1 to city k on day d via route r

# 'G(k(d))' is the set of nodes connnected to k(d) 
# 'F(k(d))' is the set of nodes k(d) is connnected to

# 'L' is set of all edges
# 'N' is set of all nodes

# 'g(i,j)' is the cost for plane i at city j
# 'p(j)' is the number of planes that can take maintenance at city j
# 'y(i)'=1, is the number of days until the due date for maintenance

# 'w(i,j,d)'=1, if maintenance taken, else 0
# 'C(i,j(d-1)k(d)r)' is the cost for plane i via j(d-1)k(d)r edge
# 'x(i,j(d-1)k(d)r)'=1, if plane i is taken via j(d-1)k(d)r edge, else 0

In [ ]:
#This is the number of cities in the network
n_c = len(df1['Origin City'].unique())

#This is the number of planes in the fleet
n_p = len(df2['Aircraft'])

#This is the number of days of planning horizon
n_d = 7 #week

In [ ]:
#Print the values of all variable
print('no. of cities',n_c)
print('no. of planes',n_p)
print('no. of days',n_d)

no. of cities 15
no. of planes 25
no. of days 7


In [ ]:
'''
create_network function initializes a 3D array for storing origin city as rows,
destination city as columns, days as depth, and existance of route as values.
This gives the possible routes for each day. 

We initially used dictionary as a form of data structure for storing the 
possible, and final routes. However, Dictionary uses associative array data 
structure that is of O(N) space complexity and a single add takes amortized O(1) 
time. Time complexity changes to O(N) when the underlying data structure needs 
to grow or shrink.
However, handling with arrays proves to be more convinient along with easy 
itteration and adding, changing values. Space complexity of an array is the same
as a dictionary, O(N). Time complexity depends on the size of the array. For 
example, an array of size N will require a time complexity of O(N).
'''
def create_network(df_new):
  A=np.zeros([n_c,n_c,n_d])
  for i in range(n_d):
    df=df_new[df_new['Day of Week']==i].copy()
    df=df.reset_index(drop=True)
    for i,li in enumerate(df['Origin City']):
      A[df['Origin City'].iloc[i]-1,df['Destination City'].iloc[i]-1]=1
  return A

network_array = create_network(df1)
print(network_array.shape)

(15, 15, 7)


In [ ]:
for i in range(7):
  print("DAY {}:".format(i),network_array[:,:,i])

DAY 0: [[1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]]
DAY 1: [[1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 0.

In [ ]:
network_array[:,:,0]

array([[1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0.],
       [1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1.],
       [0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.],
       [0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 1., 1., 0., 0.

In [ ]:
'''
g is an 2D array that provides the maintenance cost for a plane at a city.
'''
g=df2.drop(columns=['Aircraft']).to_numpy()
print(g.shape)
g

(25, 15)


array([[ 6,  1,  1, 12,  1,  8, 14,  2, 14, 10,  5, 14,  8, 15, 10],
       [15, 10,  2, 10,  2,  4, 13, 13,  2, 10,  3,  5,  5, 14,  6],
       [ 5,  4,  1, 14, 14,  6,  4,  4,  6, 14,  7,  9,  3,  5,  8],
       [13,  9, 11,  1,  8, 15, 10,  4,  6,  6,  2,  6,  7,  9,  7],
       [ 6,  1, 14, 10,  5, 14,  6,  6,  1, 12,  8, 15,  2,  6, 10],
       [ 8,  6,  2, 10,  3,  5,  8,  7, 10,  3, 14,  7, 14,  1, 10],
       [14, 11,  6, 14,  7,  9,  7, 15,  5,  4,  1,  7, 15,  5,  4],
       [15,  5,  6,  6,  2,  6, 10,  4, 13,  9, 11, 10,  4, 13,  9],
       [ 6,  1,  1, 12,  8, 15, 10,  4,  6,  1, 14, 10,  4,  6,  1],
       [ 6,  2, 10,  3, 14,  7,  9,  7,  8,  6,  2,  9,  7,  8,  6],
       [ 6,  1, 14, 10,  5,  6,  6,  2, 14, 11,  6,  6,  2, 14, 11],
       [14, 12,  5,  6,  6,  2,  6, 10, 15,  5,  6,  5,  1,  2,  1],
       [14, 11,  6, 14,  7,  9,  7, 15,  6, 15, 14,  5,  9,  6, 15],
       [ 8,  4,  1, 14, 14,  6,  6,  4,  4, 10,  6,  8,  7, 10, 10],
       [14, 11,  6, 16,  7,  9,  3

In [ ]:
'''
w is 2D array where 1 represents the maintenance check of a plane at a city on 
a day. Here the assumption is made that on every 4th day of the week the plane
takes a maintenance check.  
'''
w=np.zeros([n_p,n_c,n_d])
w[:,:,3]=1
print(w.shape)

(25, 15, 7)


In [ ]:
'''
final_array provides a 4D array with the final route schedules for each plane 
for a week
'''
final_array=np.zeros([n_p,n_c,n_c,n_d])
print(final_array.shape)

(25, 15, 15, 7)


In [ ]:
C=0 #CONSTANT cost for assigning plane

In [ ]:
(network_array[1,:,0])

array([1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.])

In [ ]:
'''
dfs function outputs a cyclicity, cost and route path for a week's schedule. It 
performs recursive depth first search optimization algorithm to minimize the 
cyclic cost of the airplane's schedule.
Here the cost for scheduling a plane on any route is considered homogenous, with
a constant value of 0.
'''
INF = 10e10

def dfs(n_p,ori,k,d,network_array):
  curr_cost = INF
  is_cyclic = False
  curr_path = []

  if d==7:
    path=[]
    if ori==k:
      path.append(k)
      cost=0
      return True,cost,path
    else:
      return False,INF,path

  else:
    for i in range(15):
      if network_array[k,i,d]==1:
        p_cyclic, p_cost, p_path = dfs(n_p,ori,i,d+1,network_array)
        if p_cyclic == True:
          is_cyclic = True
          if p_cost <= curr_cost:
            ind = i
            curr_cost = p_cost
            curr_path = []
            curr_path = p_path
            curr_path.append(i)

    if d==3 and is_cyclic==True:
      curr_cost += g[n_p,ind-1]
    return is_cyclic, curr_cost ,curr_path

In [ ]:
'''
dfs function outputs a cyclicity, cost and route path for a week's schedule. It 
performs recursive depth first search optimization algorithm to minimize the 
cyclic cost of the airplane's schedule.
Here the cost for scheduling a plane on any route is considered homogenous, with
a constant value of 0.
'''
INF = 10e10

def dfs(n_p,ori,k,d,net_arr):
  if d==6:
    path=[]
    if net_arr[ori][k][d]==1:
      path.append(k)
      cost=0
      return True,cost,path
    else:
      return False,INF,path
  else:
    curr_cost = INF
    is_cyclic = False
    curr_path = []
    for i in range(15):
      ind = i
      if net_arr[k,i,d]:
        #print(network_array[k,i,d])
        p_cyclic, p_cost, p_path = dfs(n_p,ori,i,d+1,net_arr)
        if p_cyclic == True:
          is_cyclic = True
          if p_cost <= curr_cost:
            ind = i
            curr_cost = p_cost
            curr_path = []
            curr_path = p_path
            curr_path.append(i)

    if d==4 and is_cyclic==True:
      curr_cost += g[n_p,ind-1]
    return is_cyclic, curr_cost , curr_path

In [ ]:
#check whether the dfs code is working fine
path =[]
cost = INF
cyclic,cost,path = dfs(1,10,0,0,network_array)
print (cyclic,cost,path)

True 14 [14, 14, 14, 13, 14, 13, 11]


In [ ]:
dfs(1,3,2,1,network_array)
# the code is running perfectly

(True, 14, [14, 14, 14, 13, 14, 12])

In [ ]:
# this is the final output of the heuristics
planning_schedule = []
objective_function = 0

In [ ]:
'''
The function runs for some fixed number of epochs and providing an optimal 
cyclic path for each plane. Along with the comparision to a randomdly generated
path for the planes. 
'''
import time

#flowchart
# number of iterations
num_iter = 5000
for iter in range(num_iter):
  start = time.time()
  network_array_copy_1 = network_array
  final_array_copy_1 = final_array
  objective_func_1 = 0
  planning_schedule_1=[]
  for n in range(0,n_p):
    cyclic=False
    k=1
    while cyclic!=True:
      d = 0 
      while np.sum(network_array_copy_1[k,:,d])==0:
        k = k+1
      cyclic,cost,path = dfs(n,k,k,d,network_array_copy_1)
      if(cyclic):
        planning_schedule_1.append(path)
        for i in range(len(path)-1):
          final_array_copy_1[n,path[i],path[i+1],d]=1
          network_array_copy_1[path[i],path[i+1],d]=0
          d+=1
    objective_func_1 += cost
  network_array_copy_2 = network_array
  final_array_copy_2 = final_array
  objective_func_2 = 0
  planning_schedule_2=[]
  temp = np.array([i for i in range(n_p)])
  random.shuffle(temp)
  for n in temp:
    cyclic=False
    k=1
    while cyclic!=True:
      d = 0 
      while np.sum(network_array_copy_2[k,:,d])==0:
        k = k+1
      cyclic,cost,path = dfs(n,k,k,d,network_array_copy_2)
      if(cyclic):
        planning_schedule_2.append(path)
        for i in range(len(path)-1):
          final_array_copy_2[n,path[i],path[i+1],d]=1
          network_array_copy_2[path[i],path[i+1],d]=0
          d+=1
    objective_func_2 += cost
  if objective_func_1 <= objective_func_2 :
    objective_function = objective_func_1
    final_array = final_array_copy_1
    network_array = network_array_copy_1
    planning_schedule = planning_schedule_1
  else:
    objective_function = objective_func_2
    planning_schedule = planning_schedule_2
    final_array = final_array_copy_2
    network_array = network_array_copy_2
  end =time.time()
  print('Ran successfully for iteration ',i,"and time taken till this iteration is ",(end-start))

Streaming output truncated to the last 5000 lines.
Ran successfully for iteration  1 and time taken till this iteration is 29.21572995185852
Ran successfully for iteration  2 and time taken till this iteration is 58.43145990371704
Ran successfully for iteration  3 and time taken till this iteration is 87.64718985557556
Ran successfully for iteration  4 and time taken till this iteration is 116.86291980743408
Ran successfully for iteration  5 and time taken till this iteration is 146.0786497592926
Ran successfully for iteration  6 and time taken till this iteration is 175.29437971115112
Ran successfully for iteration  7 and time taken till this iteration is 204.51010966300964
Ran successfully for iteration  8 and time taken till this iteration is 233.72583961486816
Ran successfully for iteration  9 and time taken till this iteration is 262.9415695667267
Ran successfully for iteration  10 and time taken till this iteration is 292.1572995185852
Ran successfully for iteration  11 and time 

We can see that it ran for 5000 iterations with total time taken of about 146078 seconds.

In [ ]:
# This is the final planning schedule
planning_schedule 

[[11, 11, 14, 13, 14, 12, 13],
 [2, 7, 10, 14, 5, 13, 1],
 [6, 11, 10, 8, 4, 14, 2],
 [7, 9, 5, 4, 6, 11, 8],
 [5, 8, 14, 3, 4, 10, 9],
 [12, 8, 9, 10, 6, 13, 11],
 [9, 14, 5, 10, 13, 3, 6],
 [7, 9, 11, 2, 14, 13, 1],
 [11, 8, 4, 3, 14, 5, 7],
 [11, 7, 5, 12, 8, 6, 10],
 [5, 2, 13, 1, 11, 12, 9],
 [12, 14, 3, 7, 8, 4, 9],
 [8, 13, 12, 5, 3, 2, 4],
 [10, 1, 13, 7, 8, 14, 2],
 [10, 13, 5, 9, 6, 4, 11],
 [4, 3, 12, 2, 5, 8, 7],
 [6, 10, 13, 12, 7, 2, 11],
 [10, 8, 3, 2, 6, 9, 14],
 [1, 8, 12, 4, 14, 9, 7],
 [13, 2, 6, 12, 1, 7, 11],
 [3, 5, 8, 4, 13, 1, 7],
 [8, 6, 10, 5, 11, 13, 12],
 [4, 1, 6, 10, 13, 9, 2],
 [11, 6, 12, 3, 1, 7, 9],
 [13, 5, 12, 11, 9, 6, 8]]

In [ ]:
# this is the dataframe of the final schedule
df = pd.DataFrame(planning_schedule,index=[i+1 for i in range(25)],columns=[i+1 for i in range(7)])
df

1   2   3   4   5   6   7
1   11  11  14  13  14  12  13
2    2   7  10  14   5  13   1
3    6  11  10   8   4  14   2
4    7   9   5   4   6  11   8
5    5   8  14   3   4  10   9
6   12   8   9  10   6  13  11
7    9  14   5  10  13   3   6
8    7   9  11   2  14  13   1
9   11   8   4   3  14   5   7
10  11   7   5  12   8   6  10
11   5   2  13   1  11  12   9
12  12  14   3   7   8   4   9
13   8  13  12   5   3   2   4
14  10   1  13   7   8  14   2
15  10  13   5   9   6   4  11
16   4   3  12   2   5   8   7
17   6  10  13  12   7   2  11
18  10   8   3   2   6   9  14
19   1   8  12   4  14   9   7
20  13   2   6  12   1   7  11
21   3   5   8   4  13   1   7
22   8   6  10   5  11  13  12
23   4   1   6  10  13   9   2
24  11   6  12   3   1   7   9
25  13   5  12  11   9   6   8

In [ ]:
# weekly mantainance cost for each aircraft
weekly_cost=[]
for k in range(len(planning_schedule)):
  weekly_cost.append(g[k][4])

weekly_cost

[1, 2, 14, 8, 5, 3, 7, 2, 8, 14, 5, 6, 7, 14, 7, 8, 6, 2, 10, 3, 5, 8, 7, 5, 8]

In [ ]:
# This is the value of the objective function
objective_function

207